-- MySQL Script generated by MySQL Workbench
-- mar. 06 nov. 2018 14:39:37 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pur_beurre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pur_beurre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pur_beurre` DEFAULT CHARACTER SET utf8 ;
USE `pur_beurre` ;

-- -----------------------------------------------------
-- Table `pur_beurre`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pur_beurre`.`Category` (
  `id` SMALLINT(5) UNSIGNED UNIQUE NOT NULL,
  `name_category` VARCHAR(150) UNIQUE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX ind_cat (id, name_category)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pur_beurre`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pur_beurre`.`Product` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(70) NOT NULL,
  `brand_product` VARCHAR(40) NOT NULL,
  `nutritional_note` VARCHAR(10),
  `url` VARCHAR(150) NULL DEFAULT NULL,
  `category_id` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_id` (`category_id` ASC),
  CONSTRAINT `fk_category_id`
      FOREIGN KEY (`category_id`)
      REFERENCES `pur_beurre`.`Category` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `pur_beurre`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pur_beurre`.`Store` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `name_store` VARCHAR(30) UNIQUE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pur_beurre`.`Product_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pur_beurre`.`Product_Store` (
  `store_product_id` INT(10) UNSIGNED NOT NULL,
  `store_id` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `fk_store_id` (`store_id` ASC),
  CONSTRAINT `fk_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `pur_beurre`.`Store` (`id`),
  CONSTRAINT `fk_store_product_id`
    FOREIGN KEY (`store_product_id`)
    REFERENCES `pur_beurre`.`Product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pur_beurre`.`Substitute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pur_beurre`.`Substitute` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT(10) UNSIGNED NOT NULL,
  `Substitute_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_id` (`product_id` ASC),
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `pur_beurre`.`Product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
