
CREATE SCHEMA IF NOT EXISTS pur_beurre DEFAULT CHARACTER SET utf8 ;
USE pur_beurre;

CREATE TABLE IF NOT EXISTS `pur_beurre`.`Product` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(70) NOT NULL,
  `brand_product` VARCHAR(40) NOT NULL,
  `nutritional_note` VARCHAR(10),
  `url` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS Category (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name_category VARCHAR(40) NOT NULL,
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Store (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name_store VARCHAR(30),
   (id)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Substitute (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  product_id INT UNSIGNED NOT NULL,
  CONSTRAINT fk_product_id
  FOREIGN KEY (product_id)
  REFERENCES Product(id)
)
ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Product_Store (
  store_product_id int UNSIGNED PRIMARY KEY,
  store_id SMALLINT UNSIGNED NOT NULL,
  CONSTRAINT fk_store_product_id
  FOREIGN KEY (store_product_id)
  REFERENCES Product(id),
  CONSTRAINT fk_store_id
  FOREIGN KEY (store_id)
  REFERENCES Store(id)
)
ENGINE=INNODB;
